version: "3.8"

services:
  player_api:
    build:
      context: .
    command: uvicorn api:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
    volumes:
      - .:/app

  reddit_api:
    build:
      context: .
    command: uvicorn reddit_cloud_api:reddit_app --host 0.0.0.0 --port 8002
    ports:
      - "8002:8002"
    volumes:
      - .:/app

  similar_players_api:
    build:
      context: .
    command: uvicorn recommend_similar_players:app --host 0.0.0.0 --port 8003 --reload
    ports:
      - "8003:8003"
    volumes:
      - .:/app
